# ── Ekodi.ai – Portainer Docker Compose ────────────────────
# Deploy as a Stack in Portainer
# Usage: docker compose -f ekodi-port.yml up -d
# External port: 9001 (change if already in use on your server)

version: "3.8"

services:
  # ── Ekodi Web App ──────────────────────────────────────
  ekodi-web:
    build: .
    restart: always
    ports:
      - "9001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-ekodi}:${POSTGRES_PASSWORD:-ekodi_secret}@postgres:5432/${POSTGRES_DB:-ekodi}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - JWT_SECRET=${JWT_SECRET:-change-me-jwt-secret}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - DEBUG=${DEBUG:-false}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_FROM=${SMTP_FROM:-ekodi.ai <noreply@ekodi.ai>}
      - BASE_URL=${BASE_URL:-https://ekodi.ai}
      - DATA_RETENTION_DAYS=${DATA_RETENTION_DAYS:-365}
      - EKODI_MAX_CONCURRENT=${EKODI_MAX_CONCURRENT:-20}
      - EKODI_CPU_THRESHOLD=${EKODI_CPU_THRESHOLD:-90}
      - EKODI_MEMORY_THRESHOLD=${EKODI_MEMORY_THRESHOLD:-90}
    volumes:
      - model-cache:/root/.cache
    networks:
      - ekodi-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── PostgreSQL ─────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "9002:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ekodi}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ekodi_secret}
      - POSTGRES_DB=${POSTGRES_DB:-ekodi}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ekodi-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ekodi}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Redis ──────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - ekodi-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
  model-cache:

networks:
  ekodi-net:
    driver: bridge
